export const SITE_NAME = 'Bali Journal'
export const SITE_URL = 'https://www.balijournal.com'
export const SITE_DOMAIN = 'balijournal.com'
export const COMPANY_NAME = 'PT Indonesia Oncharge Advertising'
export const COMPANY_SHORT_NAME = 'PT Oncharge'
